### ISSUE TITLE
Script stops when room is more than 10 levels above the user max.

### ISSUE THREAD

**Issue by lonerunner** [geekahedron/SteamGameAutoJoin#8]
When the room i am trying to access reaches more than 10 levels above my previous max the script stops and throws a notification 

24 Error joining game 48583: You cannot join a game that is more than 10 levels higher than the highest level you have completed.
VM1044:54 No more rooms in queue

Can it just skips that room and continue loop through other rooms until it find one to join.

**Comment by geekahedron** [comment]
That is exactly what the script does. You will only see the popup message for any error if it is the last one in your list (hence the other message, "No more rooms in queue.").
